name: "test doxygen"

on:
  push:
    branches:
      - docs/126.2-Documentation-in-github

jobs:
  analyze:
    name: Analyze on Dev
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [ 'csharp' ]

    steps:                    
      - name: "Doxygen"
        run: |
          sudo apt-get install -y doxygen
          doxygen Doxyfile



